# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rawatm blog
tagline:          'IT & Software'
description:      'Software Engineer.'
baseurl:          "/rawatm.github.io/"

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
gems: [Jekyll-gist]
paginate_path: "page:num"

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
<<<<<<< HEAD
=======
theme: jekyll-theme-midnight
>>>>>>> 2ff4944551521ad23370f313f732dfcc50856a3b
