# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rawatm blog
tagline:          'IT & Software'
description:      'Software Engineer.'
baseurl:          "/rawatm.github.io/"

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]

paginate_path: "page:num"

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
