# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Madhur Rawat
tagline:             'Software & security'
description:         'Software engineer currently working in area of linux kernel, ARM AARCHv8 architecture.'
url:                 https://github.com/rawatm
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Madhur Rawat
  url:               https://github.com/rawatm
  email:             madhur0311@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'