# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rawatm blog
tagline:          'IT & Software'
baseurl:          "/rawatm.github.io/"

paginate:         5

author:
  name:           'Madhur Rawat'
  url:            https://github.com/rawatm

paginate:         5

plugins: [jekyll-paginate]

paginate_path: "page:num"

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/rawatm
